server:
  port: 8080

logging:
  level:
    org.springframework.beans.factory: ERROR
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/evote
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect